# coding:iso-8859-9 Türkçe

from collections import Counter

s1 = Counter ('aaabbb')
s2 = Counter ('aabcccddddd')
print ("s1:", s1)
print ("s2:", s2)
print()
print ("s1+s2:", s1+s2) # İkisindeki değerleri toplar...
print ("s1-s2:", s1-s2) # İlkten ikincideki değeri düşer, 0 ve altını almaz...
print ("s1&s2:", s1&s2) # İkisinden küçük değerlisi...
print ("s1|s2:", s1|s2) # Veya, ikisinden büyük değerlisi...
