# coding:iso-8859-9 Türkçe

a = 23 # Tamsayı long
b = 47.98 # Kayan noktalı
c = 65 + 32j # Kompleks sayı
print (a, b, c)

del a, b, c
# print (a, b, c) değişkenler tanımsız hatası verir...

dizge = 'Merhaba Python Dünyası!'

print ("\n" + dizge) # Tüm dizge yazılır...
print (dizge[0]) # Dizgenin ilk karakteri yazılır...
print (dizge[2:5]) # Dizgenin [3,5] karakterleri yazılır...
print (dizge[2:]) # Dizgenin [3,] sonuna kadarı yazılır...
print (dizge * 3) # Dizge 3 kez ardışık yazılır...
print (dizge + "TEST\n") # Dizgeye ekleme yaparak yazar...

liste = [ 'abcd', 786 , 2.23, 'Nihat', 23.5E-7J, 70.2 ]
küçükListe = [123, 'Nihat']

print (liste) # Tüm listeyi yazar...
print (liste[0]) # Listenin ilk elemanını yazar...
print (liste[1:3]) # Listenin 2 ve 3. elemanlarını yazar...
print (liste[2:]) # Listenin 2.den sona kadarı yazar...
print (küçükListe * 3) # Listeyi 3 kez ardışık yazar...
print (liste + küçükListe, "\n") # Küçük listeyi listeye ekleyerek yazar...

# Liste []'li, eleman sayısı değişebilir; tüple ()'li ve değişmez...
tüple = ( 'abcd', 786 , 2.23, 'Nihat', 23.5E-7J, 70.2 )
küçükTüple = (123, 'Nihat')

print (tüple) # Tüm tüpleyi yazar...
print (tüple[0]) # Tüplenin ilk elemanını yazar...
print (tüple[1:3]) # Tüplenin 2 ve 3. elemanlarını yazar...
print (tüple[2:]) # Tüplenin 2.den sona kadarı yazar...
print (küçükTüple * 3) # Tüpleyi 3 kez ardışık yazar...
print (tüple + küçükTüple, "\n") # Küçük tüpleyi tüpleye ekleyerek yazar...

liste[2] = 1000 # Liste için geçerlidir...
# tüple[2] = 1000 # Tüple için hata mesajı verir...

sözlük = {} # Sözlük {}'lı, anahtar-değer çiftinden oluşur...
sözlük['bir'] = "Bu elemanın değeri bir'dir"
sözlük[2]     = "Bu elemanın değeri iki'dir"

küçükSözlük = {'isim': 'M.Nihat Yavaş', 'dYıl ': 1957, 'dYer': 'Yeşilyurt'}

print (sözlük['bir']) # 'bir' anahtarlı değeri yazar...
print (sözlük[2]) # 2 anahtarlı değeri yazar...
print (küçükSözlük) # Tüm küçük sözlüğü yazar...
print (küçükSözlük.keys()) # Küçük sözlüğün anahtarlarını yazar...
print (küçükSözlük.values()) # Küçük sözlüğün değerlerini yazar...